---
- name: Get Hostname
  hosts: all
  become: yes
  become_user: ec2-user
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Display hostname
      debug:
        var: hostname_output.stdout
